apiVersion: v1
kind: Service
metadata:
  name: secure-microservice
  labels:
    app: secure-microservice
spec:
  selector:
    app: secure-microservice
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
